name: Test Data Supplier Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Test on manual PR
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          SONAR_URL: ${{ secrets.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./gradlew clean sonar
      - name: Built and Test on Dependabot PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: ./gradlew clean test
